import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import (
    classification_report, confusion_matrix,
    accuracy_score, ConfusionMatrixDisplay
)
from sklearn.calibration import CalibratedClassifierCV
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('Agg')
import joblib
import os
import json

TRAINING_DATA = [
    # ── food (50 samples) ──
    ("lunch at restaurant", "food"),
    ("pizza hut order", "food"),
    ("starbucks coffee", "food"),
    ("mcdonalds burger", "food"),
    ("uber eats delivery", "food"),
    ("doordash food order", "food"),
    ("dinner at cafe", "food"),
    ("breakfast meal", "food"),
    ("grocery shopping walmart", "food"),
    ("supermarket food purchase", "food"),
    ("chipotle mexican grill", "food"),
    ("swiggy food delivery", "food"),
    ("zomato order", "food"),
    ("dominos pizza", "food"),
    ("kfc chicken meal", "food"),
    ("subway sandwich", "food"),
    ("restaurant bill payment", "food"),
    ("coffee shop purchase", "food"),
    ("bakery items bought", "food"),
    ("milk eggs bread grocery", "food"),
    ("food court mall", "food"),
    ("biryani restaurant", "food"),
    ("hotel dining", "food"),
    ("canteen lunch", "food"),
    ("snacks purchase", "food"),
    ("burger king meal", "food"),
    ("ice cream parlour", "food"),
    ("fruit vegetable market", "food"),
    ("tiffin service monthly", "food"),
    ("mess food charge", "food"),
    ("tea coffee canteen", "food"),
    ("haldirams snacks", "food"),
    ("barbeque nation dinner", "food"),
    ("food delivery app", "food"),
    ("grocery store bill", "food"),
    ("organic food store", "food"),
    ("pizza delivery home", "food"),
    ("fast food meal", "food"),
    ("chinese restaurant", "food"),
    ("south indian restaurant", "food"),
    ("salad bar lunch", "food"),
    ("juice shop", "food"),
    ("sweet shop mithai", "food"),
    ("dry fruits purchase", "food"),
    ("fish market purchase", "food"),
    ("meat shop purchase", "food"),
    ("cafe coffee day", "food"),
    ("pasta italian restaurant", "food"),
    ("sushi japanese food", "food"),
    ("food subscription box", "food"),

    # ── transport (50 samples) ──
    ("uber ride booking", "transport"),
    ("lyft cab service", "transport"),
    ("taxi fare payment", "transport"),
    ("petrol gas station", "transport"),
    ("fuel refill car", "transport"),
    ("parking fee mall", "transport"),
    ("bus ticket purchase", "transport"),
    ("train ticket booking", "transport"),
    ("metro card recharge", "transport"),
    ("flight ticket airline", "transport"),
    ("car service maintenance", "transport"),
    ("ola cab ride", "transport"),
    ("rapido bike taxi", "transport"),
    ("toll plaza payment", "transport"),
    ("auto rickshaw fare", "transport"),
    ("irctc train booking", "transport"),
    ("indigo flight booking", "transport"),
    ("airport taxi cab", "transport"),
    ("diesel fuel refill", "transport"),
    ("vehicle insurance renewal", "transport"),
    ("bike service centre", "transport"),
    ("car wash service", "transport"),
    ("driving license fee", "transport"),
    ("road tax vehicle", "transport"),
    ("tyre puncture repair", "transport"),
    ("cab booking outstation", "transport"),
    ("bus pass monthly", "transport"),
    ("railway platform ticket", "transport"),
    ("air india flight", "transport"),
    ("spicejet ticket booking", "transport"),
    ("honda car service", "transport"),
    ("bike fuel petrol", "transport"),
    ("parking ticket fine", "transport"),
    ("metro token purchase", "transport"),
    ("car rental service", "transport"),
    ("scooter rental bike", "transport"),
    ("electric vehicle charge", "transport"),
    ("highway toll fee", "transport"),
    ("flight cancellation refund", "transport"),
    ("train reservation charge", "transport"),
    ("cab airport transfer", "transport"),
    ("bike taxi rapido", "transport"),
    ("car pool share", "transport"),
    ("vehicle registration fee", "transport"),
    ("pollution certificate", "transport"),
    ("helmet purchase vehicle", "transport"),
    ("car accessories shop", "transport"),
    ("motor vehicle tax", "transport"),
    ("bus charter service", "transport"),
    ("travel agent booking", "transport"),

    # ── entertainment (50 samples) ──
    ("netflix subscription monthly", "entertainment"),
    ("spotify premium music", "entertainment"),
    ("movie ticket cinema", "entertainment"),
    ("gaming purchase store", "entertainment"),
    ("playstation game buy", "entertainment"),
    ("xbox game pass", "entertainment"),
    ("hulu subscription", "entertainment"),
    ("disney plus hotstar", "entertainment"),
    ("youtube premium", "entertainment"),
    ("amazon prime video", "entertainment"),
    ("hotstar subscription", "entertainment"),
    ("pvr cinemas ticket", "entertainment"),
    ("inox movie ticket", "entertainment"),
    ("concert ticket show", "entertainment"),
    ("gaming store purchase", "entertainment"),
    ("steam game purchase", "entertainment"),
    ("book movie online", "entertainment"),
    ("amusement park ticket", "entertainment"),
    ("bowling alley game", "entertainment"),
    ("theme park entry", "entertainment"),
    ("cricket match ticket", "entertainment"),
    ("live show ticket", "entertainment"),
    ("escape room game", "entertainment"),
    ("apple tv subscription", "entertainment"),
    ("zee5 subscription", "entertainment"),
    ("sony liv subscription", "entertainment"),
    ("alt balaji subscription", "entertainment"),
    ("voot subscription", "entertainment"),
    ("museum entry ticket", "entertainment"),
    ("zoo entry ticket", "entertainment"),
    ("night club entry", "entertainment"),
    ("pub bar bill", "entertainment"),
    ("karaoke night", "entertainment"),
    ("laser tag game", "entertainment"),
    ("board game cafe", "entertainment"),
    ("virtual reality game", "entertainment"),
    ("water park ticket", "entertainment"),
    ("comedy show ticket", "entertainment"),
    ("theatre play ticket", "entertainment"),
    ("sports match ticket", "entertainment"),
    ("ipl cricket ticket", "entertainment"),
    ("badminton court booking", "entertainment"),
    ("swimming pool entry", "entertainment"),
    ("trampoline park", "entertainment"),
    ("go karting", "entertainment"),
    ("paintball game", "entertainment"),
    ("disc golf game", "entertainment"),
    ("poker game entry", "entertainment"),
    ("chess tournament fee", "entertainment"),
    ("music concert festival", "entertainment"),

    # ── shopping (50 samples) ──
    ("amazon online purchase", "shopping"),
    ("ebay order placed", "shopping"),
    ("target store shopping", "shopping"),
    ("clothes shopping mall", "shopping"),
    ("shoes purchase store", "shopping"),
    ("fashion outlet buy", "shopping"),
    ("mall shopping spree", "shopping"),
    ("electronics store purchase", "shopping"),
    ("flipkart order delivery", "shopping"),
    ("myntra clothes buy", "shopping"),
    ("ajio fashion order", "shopping"),
    ("meesho order placed", "shopping"),
    ("online shopping cart", "shopping"),
    ("gadget purchase online", "shopping"),
    ("mobile phone buy new", "shopping"),
    ("laptop purchase store", "shopping"),
    ("headphones buy online", "shopping"),
    ("watch purchase gift", "shopping"),
    ("jewellery shopping gold", "shopping"),
    ("home decor purchase", "shopping"),
    ("furniture buy sofa", "shopping"),
    ("kitchen appliance buy", "shopping"),
    ("sports equipment purchase", "shopping"),
    ("nykaa beauty products", "shopping"),
    ("gift purchase birthday", "shopping"),
    ("snapdeal order placed", "shopping"),
    ("tata cliq shopping", "shopping"),
    ("reliance digital store", "shopping"),
    ("croma electronics store", "shopping"),
    ("big bazaar shopping", "shopping"),
    ("dmart grocery store", "shopping"),
    ("ikea furniture store", "shopping"),
    ("zara clothes store", "shopping"),
    ("hm fashion store", "shopping"),
    ("lifestyle store shopping", "shopping"),
    ("westside clothes store", "shopping"),
    ("max fashion store", "shopping"),
    ("puma shoes store", "shopping"),
    ("nike shoes purchase", "shopping"),
    ("adidas store purchase", "shopping"),
    ("decathlon sports store", "shopping"),
    ("book store purchase", "shopping"),
    ("stationery store buy", "shopping"),
    ("toy store purchase", "shopping"),
    ("cosmetics store makeup", "shopping"),
    ("perfume purchase store", "shopping"),
    ("sunglasses buy store", "shopping"),
    ("bag purchase handbag", "shopping"),
    ("wallet purchase leather", "shopping"),
    ("belt purchase store", "shopping"),

    # ── bills (50 samples) ──
    ("electricity bill payment", "bills"),
    ("water bill monthly", "bills"),
    ("internet wifi bill", "bills"),
    ("phone mobile bill", "bills"),
    ("broadband subscription monthly", "bills"),
    ("insurance premium payment", "bills"),
    ("utility payment online", "bills"),
    ("airtel recharge prepaid", "bills"),
    ("jio recharge plan", "bills"),
    ("bsnl bill payment", "bills"),
    ("gas cylinder bill", "bills"),
    ("dth recharge tata sky", "bills"),
    ("credit card bill payment", "bills"),
    ("emi payment loan", "bills"),
    ("postpaid bill monthly", "bills"),
    ("electricity board payment", "bills"),
    ("municipal water tax", "bills"),
    ("maintenance charges society", "bills"),
    ("cable tv bill", "bills"),
    ("telephone landline bill", "bills"),
    ("vi vodafone bill", "bills"),
    ("loan emi payment", "bills"),
    ("house tax property tax", "bills"),
    ("society maintenance fee", "bills"),
    ("prepaid recharge mobile", "bills"),
    ("dish tv recharge", "bills"),
    ("sun direct dth", "bills"),
    ("car insurance premium", "bills"),
    ("life insurance premium", "bills"),
    ("health insurance premium", "bills"),
    ("home insurance payment", "bills"),
    ("two wheeler insurance", "bills"),
    ("solar panel bill", "bills"),
    ("gas pipeline bill", "bills"),
    ("water tanker bill", "bills"),
    ("garbage collection fee", "bills"),
    ("apartment maintenance charge", "bills"),
    ("wifi router rental", "bills"),
    ("landline broadband bill", "bills"),
    ("mobile data plan", "bills"),
    ("annual subscription fee", "bills"),
    ("cloud storage subscription", "bills"),
    ("antivirus subscription", "bills"),
    ("microsoft office subscription", "bills"),
    ("adobe subscription monthly", "bills"),
    ("google workspace bill", "bills"),
    ("domain hosting renewal", "bills"),
    ("electricity advance payment", "bills"),
    ("water advance deposit", "bills"),
    ("phone plan upgrade", "bills"),

    # ── rent (40 samples) ──
    ("monthly rent payment", "rent"),
    ("house rent transfer", "rent"),
    ("apartment lease payment", "rent"),
    ("mortgage payment bank", "rent"),
    ("property rent monthly", "rent"),
    ("flat rent paid", "rent"),
    ("room rent payment", "rent"),
    ("pg accommodation rent", "rent"),
    ("hostel fee payment", "rent"),
    ("housing payment monthly", "rent"),
    ("landlord rent transfer", "rent"),
    ("office rent payment", "rent"),
    ("commercial lease rent", "rent"),
    ("deposit advance rent", "rent"),
    ("rental payment transfer", "rent"),
    ("studio apartment rent", "rent"),
    ("1bhk flat rent", "rent"),
    ("2bhk apartment rent", "rent"),
    ("shared house rent", "rent"),
    ("guesthouse rent payment", "rent"),
    ("serviced apartment rent", "rent"),
    ("coliving space rent", "rent"),
    ("dormitory rent hostel", "rent"),
    ("vacation rental payment", "rent"),
    ("airbnb payment rent", "rent"),
    ("shop rent commercial", "rent"),
    ("warehouse rent monthly", "rent"),
    ("garage rent parking", "rent"),
    ("storage unit rent", "rent"),
    ("coworking space rent", "rent"),
    ("house lease renewal", "rent"),
    ("rental agreement deposit", "rent"),
    ("advance rent payment", "rent"),
    ("subletting rent paid", "rent"),
    ("tenant rent collection", "rent"),
    ("property management fee", "rent"),
    ("real estate agent fee", "rent"),
    ("house shifting charges", "rent"),
    ("moving company charges", "rent"),
    ("packers movers payment", "rent"),

    # ── health (50 samples) ──
    ("doctor consultation fee", "health"),
    ("hospital bill payment", "health"),
    ("pharmacy medicine purchase", "health"),
    ("dental checkup payment", "health"),
    ("gym membership monthly", "health"),
    ("fitness subscription app", "health"),
    ("health insurance premium", "health"),
    ("therapy session payment", "health"),
    ("clinic visit charges", "health"),
    ("medical test payment", "health"),
    ("apollo pharmacy order", "health"),
    ("1mg medicine order", "health"),
    ("netmeds prescription order", "health"),
    ("yoga class monthly", "health"),
    ("physiotherapy session", "health"),
    ("eye checkup optician", "health"),
    ("blood test lab", "health"),
    ("vaccination hospital", "health"),
    ("ayurveda medicine purchase", "health"),
    ("health supplement protein", "health"),
    ("surgery hospital bill", "health"),
    ("ambulance charge emergency", "health"),
    ("mental health counselling", "health"),
    ("dietitian consultation fee", "health"),
    ("medical equipment purchase", "health"),
    ("orthopedic consultation", "health"),
    ("dermatologist visit fee", "health"),
    ("cardiologist consultation", "health"),
    ("pathology lab test", "health"),
    ("mri scan charges", "health"),
    ("xray charges hospital", "health"),
    ("ecg test charges", "health"),
    ("ultrasound scan fee", "health"),
    ("covid test charges", "health"),
    ("vitamin supplement purchase", "health"),
    ("protein powder health", "health"),
    ("meditation app subscription", "health"),
    ("cult fit subscription", "health"),
    ("crossfit gym fee", "health"),
    ("zumba class fee", "health"),
    ("pilates class fee", "health"),
    ("swimming class fee", "health"),
    ("sports injury treatment", "health"),
    ("icu hospital charges", "health"),
    ("nursing home charges", "health"),
    ("chemist shop medicine", "health"),
    ("homeopathy medicine purchase", "health"),
    ("acupuncture treatment fee", "health"),
    ("spa wellness treatment", "health"),
    ("health checkup package", "health"),

    # ── education (50 samples) ──
    ("school fees payment", "education"),
    ("college tuition fees", "education"),
    ("university admission fee", "education"),
    ("udemy course purchase", "education"),
    ("coursera subscription", "education"),
    ("book purchase study", "education"),
    ("coaching class fee", "education"),
    ("online learning platform", "education"),
    ("exam registration fee", "education"),
    ("stationery notebook pen", "education"),
    ("byju subscription", "education"),
    ("unacademy course", "education"),
    ("skill development course", "education"),
    ("programming course online", "education"),
    ("certification exam fee", "education"),
    ("library membership fee", "education"),
    ("workshop registration fee", "education"),
    ("seminar conference fee", "education"),
    ("language learning app", "education"),
    ("tutoring fee private", "education"),
    ("college bus fee", "education"),
    ("hostel college fee", "education"),
    ("lab fee college", "education"),
    ("internship course fee", "education"),
    ("competitive exam fee", "education"),
    ("gate exam fee", "education"),
    ("cat exam registration", "education"),
    ("upsc exam fee", "education"),
    ("gre exam fee", "education"),
    ("toefl exam payment", "education"),
    ("ielts exam fee", "education"),
    ("harvard online course", "education"),
    ("mit opencourseware", "education"),
    ("linkedin learning subscription", "education"),
    ("pluralsight subscription", "education"),
    ("codecademy pro subscription", "education"),
    ("datacamp subscription", "education"),
    ("skillshare subscription", "education"),
    ("masterclass subscription", "education"),
    ("school uniform purchase", "education"),
    ("school bag purchase", "education"),
    ("calculator scientific purchase", "education"),
    ("drawing instruments set", "education"),
    ("craft material school", "education"),
    ("project material purchase", "education"),
    ("printing binding charges", "education"),
    ("photocopy charges college", "education"),
    ("notes purchase study", "education"),
    ("reference book purchase", "education"),
    ("magazine subscription study", "education"),

    # ── salary (40 samples) ──
    ("monthly salary credited", "salary"),
    ("salary payment received", "salary"),
    ("payroll deposit bank", "salary"),
    ("wage credited account", "salary"),
    ("income salary transfer", "salary"),
    ("employer salary payment", "salary"),
    ("net salary received", "salary"),
    ("ctc salary credited", "salary"),
    ("bonus salary payment", "salary"),
    ("increment salary received", "salary"),
    ("stipend credited account", "salary"),
    ("fellowship amount received", "salary"),
    ("salary hike credited", "salary"),
    ("joining bonus payment", "salary"),
    ("performance bonus credited", "salary"),
    ("annual bonus payment", "salary"),
    ("diwali bonus salary", "salary"),
    ("gratuity payment received", "salary"),
    ("leave encashment payment", "salary"),
    ("overtime salary payment", "salary"),
    ("part time salary", "salary"),
    ("internship stipend received", "salary"),
    ("research stipend payment", "salary"),
    ("government salary payment", "salary"),
    ("psu salary credited", "salary"),
    ("bank salary transfer", "salary"),
    ("neft salary received", "salary"),
    ("imps salary credit", "salary"),
    ("salary advance received", "salary"),
    ("arrears salary payment", "salary"),
    ("variable pay credited", "salary"),
    ("incentive payment salary", "salary"),
    ("commission salary payment", "salary"),
    ("sales incentive payment", "salary"),
    ("monthly stipend payment", "salary"),
    ("weekly wage payment", "salary"),
    ("daily wage received", "salary"),
    ("contract salary payment", "salary"),
    ("probation salary credited", "salary"),
    ("confirmation bonus salary", "salary"),

    # ── freelance (40 samples) ──
    ("freelance payment received", "freelance"),
    ("client project payment", "freelance"),
    ("consulting fee received", "freelance"),
    ("contract work payment", "freelance"),
    ("upwork payment received", "freelance"),
    ("fiverr earning credited", "freelance"),
    ("freelancer payment received", "freelance"),
    ("gig payment received", "freelance"),
    ("project milestone payment", "freelance"),
    ("invoice payment received", "freelance"),
    ("part time work payment", "freelance"),
    ("content writing payment", "freelance"),
    ("design work payment", "freelance"),
    ("development project payment", "freelance"),
    ("youtube monetization payment", "freelance"),
    ("blog income received", "freelance"),
    ("affiliate marketing payment", "freelance"),
    ("referral bonus received", "freelance"),
    ("photography payment client", "freelance"),
    ("video editing payment", "freelance"),
    ("social media management fee", "freelance"),
    ("seo service payment", "freelance"),
    ("data entry work payment", "freelance"),
    ("translation work payment", "freelance"),
    ("tutoring payment received", "freelance"),
    ("music production payment", "freelance"),
    ("logo design payment", "freelance"),
    ("app development payment", "freelance"),
    ("web design client payment", "freelance"),
    ("copywriting payment received", "freelance"),
    ("podcast sponsorship payment", "freelance"),
    ("instagram sponsorship payment", "freelance"),
    ("brand collaboration payment", "freelance"),
    ("dropshipping profit received", "freelance"),
    ("etsy shop payment", "freelance"),
    ("online course sale", "freelance"),
    ("ebook sale income", "freelance"),
    ("stock photo sale", "freelance"),
    ("template sale income", "freelance"),
    ("plugin sale payment", "freelance"),

    # ── investment (40 samples) ──
    ("stock market purchase", "investment"),
    ("crypto bitcoin investment", "investment"),
    ("mutual fund sip", "investment"),
    ("zerodha stock buy", "investment"),
    ("groww investment app", "investment"),
    ("dividend received account", "investment"),
    ("interest earned savings", "investment"),
    ("fixed deposit bank", "investment"),
    ("gold investment purchase", "investment"),
    ("trading profit received", "investment"),
    ("nps contribution yearly", "investment"),
    ("ppf deposit yearly", "investment"),
    ("rd recurring deposit", "investment"),
    ("etf purchase zerodha", "investment"),
    ("share market trading", "investment"),
    ("angel broking investment", "investment"),
    ("upstox trading platform", "investment"),
    ("sovereign gold bond", "investment"),
    ("real estate investment", "investment"),
    ("cryptocurrency ethereum", "investment"),
    ("bitcoin purchase crypto", "investment"),
    ("dogecoin investment crypto", "investment"),
    ("nifty index fund", "investment"),
    ("sensex etf purchase", "investment"),
    ("smallcap fund sip", "investment"),
    ("largecap mutual fund", "investment"),
    ("elss tax saving fund", "investment"),
    ("liquid fund investment", "investment"),
    ("debt fund purchase", "investment"),
    ("hybrid fund investment", "investment"),
    ("ipo application payment", "investment"),
    ("rights issue payment", "investment"),
    ("stock dividend reinvest", "investment"),
    ("gold etf purchase", "investment"),
    ("silver investment purchase", "investment"),
    ("platinum investment", "investment"),
    ("us stocks investment", "investment"),
    ("nasdaq etf purchase", "investment"),
    ("international fund investment", "investment"),
    ("commodity trading profit", "investment"),
]

MODEL_PATH            = os.path.join(os.path.dirname(__file__), "ml_model.joblib")
METRICS_PATH          = os.path.join(os.path.dirname(__file__), "ml_metrics.json")
CONFUSION_MATRIX_PATH = os.path.join(os.path.dirname(__file__), "confusion_matrix.png")


def train_and_save():
    print("Training ML categorization model...")

    df = pd.DataFrame(TRAINING_DATA, columns=["description", "category"])
    X  = df["description"]
    y  = df["category"]

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )

    nb_pipeline = Pipeline([
        ("tfidf", TfidfVectorizer(ngram_range=(1, 2), min_df=1, max_features=8000, sublinear_tf=True)),
        ("clf",   MultinomialNB(alpha=0.05)),
    ])

    svm_pipeline = Pipeline([
        ("tfidf", TfidfVectorizer(ngram_range=(1, 2), min_df=1, max_features=8000, sublinear_tf=True)),
        ("clf",   CalibratedClassifierCV(LinearSVC(max_iter=2000, C=1.0))),
    ])

    nb_pipeline.fit(X_train, y_train)
    svm_pipeline.fit(X_train, y_train)

    nb_acc  = accuracy_score(y_test, nb_pipeline.predict(X_test))
    svm_acc = accuracy_score(y_test, svm_pipeline.predict(X_test))

    print(f"Naive Bayes accuracy: {nb_acc:.2%}")
    print(f"SVM accuracy:         {svm_acc:.2%}")

    best_pipeline = svm_pipeline if svm_acc >= nb_acc else nb_pipeline
    best_name     = "SVM" if svm_acc >= nb_acc else "Naive Bayes"
    best_acc      = max(nb_acc, svm_acc)
    print(f"Using: {best_name}")

    cv_scores = cross_val_score(best_pipeline, X, y, cv=5, scoring="accuracy")
    print(f"Cross-validation: {cv_scores.mean():.2%} +/- {cv_scores.std():.2%}")

    y_pred = best_pipeline.predict(X_test)
    report = classification_report(y_test, y_pred, output_dict=True)
    print("\nClassification Report:")
    print(classification_report(y_test, y_pred))

    metrics = {
        "model":            best_name,
        "accuracy":         round(best_acc, 4),
        "nb_accuracy":      round(nb_acc, 4),
        "svm_accuracy":     round(svm_acc, 4),
        "cv_mean":          round(float(cv_scores.mean()), 4),
        "cv_std":           round(float(cv_scores.std()), 4),
        "training_samples": len(X_train),
        "test_samples":     len(X_test),
        "categories":       sorted(df["category"].unique().tolist()),
        "report":           report,
    }
    with open(METRICS_PATH, "w") as f:
        json.dump(metrics, f, indent=2)
    print(f"Metrics saved → {METRICS_PATH}")

    labels  = sorted(df["category"].unique())
    cm      = confusion_matrix(y_test, y_pred, labels=labels)
    fig, ax = plt.subplots(figsize=(14, 12))
    disp    = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=labels)
    disp.plot(ax=ax, colorbar=True, cmap="Blues")
    ax.set_title(
        f"Confusion Matrix — {best_name}  |  Accuracy: {best_acc:.2%}",
        fontsize=14, pad=20
    )
    plt.xticks(rotation=45, ha="right", fontsize=10)
    plt.yticks(fontsize=10)
    plt.tight_layout()
    plt.savefig(CONFUSION_MATRIX_PATH, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"Confusion matrix saved → {CONFUSION_MATRIX_PATH}")

    joblib.dump(best_pipeline, MODEL_PATH)
    print(f"Model saved → {MODEL_PATH}")
    print(f"\nDone! Accuracy: {best_acc:.2%}")
    return metrics


if __name__ == "__main__":
    train_and_save()